FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:2.8.0-gpu-py39-cu112-ubuntu20.04-sagemaker

COPY tf2_cifar10_sm.py /opt/ml/code/tf2_cifar10_sm.py

ENTRYPOINT ["python", "/opt/ml/code/tf2_cifar10_sm.py"]