FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:2.8.0-cpu-py39-ubuntu20.04-e3

COPY tf2_cifar10_eks.py /opt/ml/code/tf2_cifar10_eks.py

ENTRYPOINT ["python", "/opt/ml/code/tf2_cifar10_eks.py"]